### ISSUE TITLE
Output strats to json?

### ISSUE THREAD

**Issue by cooljddj** [BeeeQueue/stratroulette-net#10]
I make discord bots and just wondering if you could make something that out puts all the strats to a url?

**Comment by beeequeue** [comment]
You can get all of the currently available Strats in JSON format from [/get/all](http://stratroulette.net/get/all)!

You can also get specific strats by using /get/:uid.

There are currently no rate limits, so please be kind and do not beat these poor endpoints to death with requests. 🌞

**Comment by cooljddj** [comment]
I shal not, its only for a private bot
thanks
